//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5485
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.sandigital.sharepoint.webparts.v2.Webparts.AgrupadoraPastas {
    using System.Web;
    using System.Text.RegularExpressions;
    using Microsoft.SharePoint.WebPartPages;
    using Microsoft.SharePoint.WebControls;
    using System.Web.Security;
    using Microsoft.SharePoint.Utilities;
    using System.Web.UI;
    using System;
    using System.Web.UI.WebControls;
    using System.Collections.Specialized;
    using Microsoft.SharePoint;
    using System.Collections;
    using System.Web.Profile;
    using System.Text;
    using System.Web.Caching;
    using System.Configuration;
    using System.Web.UI.WebControls.WebParts;
    using System.Web.SessionState;
    using System.Web.UI.HtmlControls;
    
    
    public partial class AgrupadoraPastas {
        
        protected global::System.Web.UI.WebControls.Label lblHack;
        
        protected global::System.Web.UI.WebControls.Label lblErro;
        
        protected global::System.Web.UI.WebControls.Literal ltDiv1;
        
        protected global::System.Web.UI.WebControls.Literal ltSaida;
        
        protected global::System.Web.UI.WebControls.Literal ltDiv2;
        
        public static implicit operator global::System.Web.UI.TemplateControl(AgrupadoraPastas target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControllblHack() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.lblHack = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lblHack";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControllblErro() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.lblErro = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lblErro";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Literal @__BuildControlltDiv1() {
            global::System.Web.UI.WebControls.Literal @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Literal();
            this.ltDiv1 = @__ctrl;
            @__ctrl.ID = "ltDiv1";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Literal @__BuildControlltSaida() {
            global::System.Web.UI.WebControls.Literal @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Literal();
            this.ltSaida = @__ctrl;
            @__ctrl.ID = "ltSaida";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Literal @__BuildControlltDiv2() {
            global::System.Web.UI.WebControls.Literal @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Literal();
            this.ltDiv2 = @__ctrl;
            @__ctrl.ID = "ltDiv2";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControlTree(global::com.sandigital.sharepoint.webparts.v2.Webparts.AgrupadoraPastas.AgrupadoraPastas @__ctrl) {
            global::System.Web.UI.WebControls.Label @__ctrl1;
            @__ctrl1 = this.@__BuildControllblHack();
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n"));
            global::System.Web.UI.WebControls.Label @__ctrl2;
            @__ctrl2 = this.@__BuildControllblErro();
            @__parser.AddParsedSubObject(@__ctrl2);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n<div id=\'"));
            global::System.Web.UI.WebControls.Literal @__ctrl3;
            @__ctrl3 = this.@__BuildControlltDiv1();
            @__parser.AddParsedSubObject(@__ctrl3);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"'></div>

<script type=""application/html-template"" id=""wpa-header"">
<table style=""width:100%"">
</script>

<script type=""application/html-template"" id=""wpa-pasta"">

<tr class=""grupo_{{idx_pai}}"" style=""{{vis}}"" >
	<td style=""padding-left:{{nivel}}px"">
		<table style=""width:100%"">
			<tr>
				<td style="""">
				<img border=""0"" alt=""{{Nome}}"" title=""{{Nome}}"" src=""/_layouts/images/folder.gif""><a href=""javascript:"" onclick=""expandir('{{idx_pasta}}');return false;"" class=""trigger_{{idx_pasta}}""><img src=""/_layouts/images/plus.gif"" border=""0""></a> <strong>&nbsp; {{Nome}}</strong>
				</td>
			</tr>
			
				{{Pastas}}
				{{Arquivos}}
								
		</table>
	</td>
</tr>
</script>

<script type=""application/html-template"" id=""wpa-arquivo"">


<!-- inicio arquivo-->
<tr class=""grupo_{{idx_pai}}"" style=""display:none;{{vis}}""  >
	<td style=""padding-left:{{nivel}}px;"" >
		<a href=""{{url}}"">
			<img src=""/_layouts/images/{{Icone}}"" alt=""{{Titulo}}"" /> &nbsp;  {{Titulo}}
		</a>
	</td>
</tr>
<!-- fim arquivo -->

</script>

<script type=""application/html-template"" id=""wpa-footer"">
</table>
</script>




<script type=""text/javascript"">

    (function () {

        var strJson = '"));
            global::System.Web.UI.WebControls.Literal @__ctrl4;
            @__ctrl4 = this.@__BuildControlltSaida();
            @__parser.AddParsedSubObject(@__ctrl4);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"';
        var arrPastas = JSON.parse(strJson);



        function getHtmlPastas(arrPastas, inicio) {
            var htmlSaida = """";

            $(arrPastas).each(function (idx, obj) {

                htmlSaida += $(""#wpa-pasta"").html()
                .replace(/{{Nome}}/g, obj.Pasta)
                .replace(/{{idx_pasta}}/g, obj.idx_pasta)
                .replace(/{{idx_pai}}/g, obj.idx_pai)
                .replace(/{{Pastas}}/g, obj.Pastas.length == 0 ? """" : """" + getHtmlPastas(obj.Pastas, false) + """")
                .replace(/{{Arquivos}}/g, obj.Arquivos.length == 0 ? """" : """" + getHtmlArquivos(obj.Arquivos, obj.idx_pasta, inicio ) + """")
                .replace(/{{vis}}/g, inicio ? """" : ""display:none"")
                .replace(/{{nivel}}/g, obj.nivel * 5);


            });	//each

            return htmlSaida;
        }

        function getHtmlArquivos(arrArquivos, idx_pai, inicio ) {


            var htmlSaida = """";
            $(arrArquivos).each(function (idx, obj) {

                htmlSaida += $(""#wpa-arquivo"").html()
                .replace(/{{Titulo}}/g, obj.Titulo)
                .replace(/{{url}}/g, obj.url)
                .replace(/{{Icone}}/g, obj.Icone)
                .replace(/{{idx_pai}}/g, idx_pai)
                .replace(/{{vis}}/g, inicio ? """" : ""display:none"")

                ;

            });//arrArq

            return htmlSaida;
        }

        
        var dvSaida = $('"));
            global::System.Web.UI.WebControls.Literal @__ctrl5;
            @__ctrl5 = this.@__BuildControlltDiv2();
            @__parser.AddParsedSubObject(@__ctrl5);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"');

         //arrPastas
        var htmlSaida = $(""#wpa-header"").html();

        $(arrPastas).each(function (idxP1, objP1) {

            //desenha a pasta 
            htmlSaida += getHtmlPastas(objP1, true);

        });//P1.Each

        htmlSaida += $(""#wpa-footer"").html();

        $(dvSaida).html(htmlSaida);

     })();





</script>"));
        }
        
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
